<a href="https://colab.research.google.com/github/adityaaaa342/Pattern-Recognition-/blob/main/practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
customers = pd.DataFrame({
    "Customer": ["C1", "C2", "C3", "C4", "C5"],
    "Annual_Spend": [5000, 5500, 7000, 4800, 6500],
    "Purchase_Frequency": [20, 22, 30, 18, 28],
    "Rating": [4.5, 4.7, 4.8, 4.2, 4.6],
    "Browsing_Time": [60, 65, 80, 55, 75]
})

customers

,Customer,Annual_Spend,Purchase_Frequency,Rating,Browsing_Time
0,C1,5000,20,4.5,60
1,C2,5500,22,4.7,65
2,C3,7000,30,4.8,80
3,C4,4800,18,4.2,55
4,C5,6500,28,4.6,75


In [5]:
features = customers.iloc[:,1:].values

print(features)

[[5.0e+03 2.0e+01 4.5e+00 6.0e+01]
 [5.5e+03 2.2e+01 4.7e+00 6.5e+01]
 [7.0e+03 3.0e+01 4.8e+00 8.0e+01]
 [4.8e+03 1.8e+01 4.2e+00 5.5e+01]
 [6.5e+03 2.8e+01 4.6e+00 7.5e+01]]


In [6]:
for i in range(len(customers)):
    for j in range(i+1,len(customers)):
        dist = np.linalg.norm(features[i]-features[j])
        print(customers["Customer"][i],"-",customers["Customer"][j],"=",round(dist,2))

C1 - C2 = 500.03
C1 - C3 = 2000.13
C1 - C4 = 200.07
C1 - C5 = 1500.1
C2 - C3 = 1500.1
C2 - C4 = 700.08
C2 - C5 = 1000.07
C3 - C4 = 2200.17
C3 - C5 = 500.03
C4 - C5 = 1700.15


In [7]:
cos_sim = cosine_similarity(features)

for i in range(len(customers)):
    for j in range(i+1,len(customers)):
        print(customers["Customer"][i],"-",customers["Customer"][j],"=",round(cos_sim[i][j],4))

C1 - C2 = 1.0
C1 - C3 = 1.0
C1 - C4 = 1.0
C1 - C5 = 1.0
C2 - C3 = 1.0
C2 - C4 = 1.0
C2 - C5 = 1.0
C3 - C4 = 1.0
C3 - C5 = 1.0
C4 - C5 = 1.0


In [9]:
sequences = {
    "C1":"ELECTRONICSBOOKS",
    "C2":"ELECTRONICSGAMES",
    "C3":"BOOKSCLOTHING",
    "C4":"ELECTRONICSBOOKS",
    "C5":"BOOKSGAMES"
}

for c,s in sequences.items():
    print(c,":",s)

C1 : ELECTRONICSBOOKS
C2 : ELECTRONICSGAMES
C3 : BOOKSCLOTHING
C4 : ELECTRONICSBOOKS
C5 : BOOKSGAMES


In [10]:
def edit_distance(s1,s2):

    m,n=len(s1),len(s2)

    dp=[[0]*(n+1) for _ in range(m+1)]

    for i in range(m+1):
        dp[i][0]=i

    for j in range(n+1):
        dp[0][j]=j

    for i in range(1,m+1):
        for j in range(1,n+1):

            if s1[i-1]==s2[j-1]:
                dp[i][j]=dp[i-1][j-1]
            else:
                dp[i][j]=1+min(
                    dp[i-1][j],
                    dp[i][j-1],
                    dp[i-1][j-1]
                )

    return dp[m][n]

In [11]:
keys=list(sequences.keys())

for i in range(len(keys)):
    for j in range(i+1,len(keys)):
        d=edit_distance(sequences[keys[i]],sequences[keys[j]])
        print(keys[i],"-",keys[j],"=",d)

C1 - C2 = 4
C1 - C3 = 15
C1 - C4 = 0
C1 - C5 = 13
C2 - C3 = 15
C2 - C4 = 4
C2 - C5 = 9
C3 - C4 = 15
C3 - C5 = 8
C4 - C5 = 13
